[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/assl-embeddings.json"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200